home/urls.py
from django.urls import path
from . import views
from .views import SearchResultsView

app_name = "home"
urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('snippets/', SearchResultsView.as_view(), name="snippets_view"),
    path('snippet_code/<str:snip>', views.snippet_view, name="snippet_view"),
    path('snippet_code/edit/<str:snipedit>', views.edit_snippet, name="edit_snippet")
]

snipsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Notes(models.Model):
    title = models.TextField(unique=True)
    date = models.BinaryField()
    note = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'notes'


class Quotes(models.Model):
    quote = models.TextField(unique=True, blank=True, null=True)
    author = models.TextField(blank=True, null=True)
    genre = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'quotes'


class Snippet(models.Model):
    title = models.CharField(max_length=255, unique=True)
    code = models.TextField(unique=True)
    date = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'snippet'

    def __str__(self):
        return self.title


class Theme(models.Model):
    color = models.TextField(unique=True, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'theme'

snipsite/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Notes(models.Model):
    id = models.AutoField(blank=True, null=True)
    title = models.TextField(unique=True)
    date = models.BinaryField()
    note = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'notes'


class Quotes(models.Model):
    id = models.AutoField()
    quote = models.TextField(unique=True, blank=True, null=True)
    author = models.TextField(blank=True, null=True)
    genre = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'quotes'


class Snippet(models.Model):
    id = models.AutoField()
    title = models.CharField(unique=True)
    code = models.TextField(unique=True)
    date = models.CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'snippet'


class Theme(models.Model):
    color = models.TextField(unique=True, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'theme'

home/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from django.views.generic import DetailView
from .models import Snippet
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def home_view(request):
    if request.method == "POST":
        # print(request.POST.get("data"))
        return redirect("home:snippets_view")
    return render(request, "index.html")


@csrf_exempt
def snippets_view(request):
    if request.method == "get":
        snippets = Snippet.objects.filter(title__icontains=request.GET.get("data"))
        context = {"snippets": snippets}
        print(context)
        return render(request, "snippets_list.html", context)
    else:
        return render(request, "index.html")


class SearchResultsView(ListView):
    model = Snippet
    template_name = "snippets_list.html"

    @csrf_exempt
    def get_queryset(self):
        query = self.request.GET.get("data")
        print(query)
        return Snippet.objects.filter(title__icontains=query)

@csrf_exempt
def snippet_view(request, snip):
    snippet = Snippet.objects.get(title=snip)
    context = {'snippet': snippet}

    return render(request, "snippet_code.html", context)


def edit_snippet(request, snipedit):
    print("Edit Snip")

home/templates/home/edit_snippet.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>GC · Snippets</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">

      <link rel="stylesheet" href="{% static 'css/styles/default.min.css' %}">





<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  {% include 'head.html' %}
  
    <h4 style="color: white; text-align: right; text-style: underline; font-family: monospace">>>>> {{ snippet.title }}</h4>
    <pre style="color: white; text-align: left; font-family: monospace"><code class="language-python">
    
    </code></pre>

  </tbody>

</table>
  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@GoofyCoda</a>.</p>
  </footer>
</div>


    <script src="{% static 'js/highlight.min.js' %}"></script>
    <script>hljs.highlightAll();</script>
  </body>
</html>

home/templates/home/head.html
{% load static %}
<header class="mb-auto">
    <div>
        <a class="navbar-brand" href="{% url 'home:home_view' %}">
            <img src="{% static 'img/logo.png' %}" alt="" width="40" height="40">
          </a>
      <h3 class="float-md-start mb-0">GC-Snippets</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a>
        <a class="nav-link fw-bold py-1 px-0" href="#">Add New Snippet</a>
        <a class="nav-link fw-bold py-1 px-0" href="#">Notes</a>
      </nav>
    </div>
  </header>

home/templates/home/index.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Cover Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">

    

    

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/logo.png' %}" alt="" width="40" height="40">
          </a>
      <h3 class="float-md-start mb-0">GC-Snippets</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a>
        <a class="nav-link fw-bold py-1 px-0" href="#">Add New Snippet</a>
        <a class="nav-link fw-bold py-1 px-0" href="#">Notes</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Ask me!</h1>
    <form class="d-flex" role="search" action="{% url 'home:snippets_view' %}" method="get">

        <input class="form-control me-2" name="data" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>


    
  </body>
</html>

home/templates/home/snippet_code.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>GC · Snippets</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">

      <link rel="stylesheet" href="{% static 'css/styles/default.min.css' %}">





<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  {% include 'head.html' %}

    <h4 style="color: white; text-align: right; text-style: underline; font-family: monospace">>>>> {{ snippet.title }}</h4>
    <pre style="color: white; text-align: left; font-family: monospace"><code class="language-python">
    {{ snippet.code }}
    </code></pre>
    <a href="{% url 'home:edit_snippet' snippet.ti %}">Edit</a>
  </tbody>

</table>
  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@GoofyCoda</a>.</p>
  </footer>
</div>


    <script src="{% static 'js/highlight.min.js' %}"></script>
    <script>hljs.highlightAll();</script>
  </body>
</html>

home/templates/home/snippets_list.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Cover Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  {% include 'head.html' %}


  <table class="table" style="color: white; text-align: left;">
    <thead>
      <tr>

        <th scope="col">Snippet title</th>
        <th scope="col">Date added</th>
        <th scope="col">Uploaded By</th>
      </tr>
    </thead>

  <tbody>
    {% for snippet in object_list %}
    <tr>

        <td><a href="{% url 'home:snippet_view' snippet.title %}" style = "text-decoration:none; color: #e2f113;">{{snippet.title}}</a></td>
      <td>{{snippet.date}}</td>
      <td>Cathbert</td>
    </tr>
    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
  </tbody>

</table>
  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>



  </body>
</html>